# Generated by Django 6.0.3 on 2026-04-02 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='M.B Shifa Clinic', max_length=100)),
                ('address', models.CharField(default='21, Deeramadi Street, Pernambut, Tamil Nadu - 635810', max_length=255)),
                ('latitude', models.FloatField(default=12.9535)),
                ('longitude', models.FloatField(default=78.8504)),
                ('average_consultation_time_minutes', models.IntegerField(default=15)),
                ('max_tokens_per_day', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.IntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactive (Outside Range)'), ('ACTIVE', 'Active (Waiting)'), ('SERVING', 'Currently Serving'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('SKIPPED', 'Skipped')], default='INACTIVE', max_length=15)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('is_priority', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='queue_board.patient')),
            ],
            options={
                'ordering': ['-is_priority', 'token_number'],
                'unique_together': {('token_number', 'date')},
            },
        ),
    ]
