# Generated by Django 6.0.3 on 2026-04-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='department',
            field=models.CharField(choices=[('GENERAL', 'General Physician'), ('PEDIATRICS', 'Pediatrics'), ('DENTAL', 'Dental')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='clinicsetting',
            name='address',
            field=models.CharField(default='WPP8+HF Peranampattu, Tamil Nadu 635810', max_length=255),
        ),
        migrations.AlterField(
            model_name='clinicsetting',
            name='latitude',
            field=models.FloatField(default=12.9364375),
        ),
        migrations.AlterField(
            model_name='clinicsetting',
            name='longitude',
            field=models.FloatField(default=78.7161875),
        ),
    ]
